version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: cashier_db
    environment:
      POSTGRES_DB: cashier_db
      POSTGRES_USER: cashier_user
      POSTGRES_PASSWORD: cashier_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cashier_user -d cashier_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
